FPS		= 60

----CONNECTIP-------
REQUEST_REGISTER_IP = "http://222.128.46.215:8088/";

---- Screen Info ----

SCREEN_WIDTH		= 1136
SCREEN_HEIGHT		= 640

SCREEN_WIDTH_HALF	= SCREEN_WIDTH / 2
SCREEN_HEIGHT_HALF	= SCREEN_HEIGHT / 2

---- Touch Event Type ----

TOUCH_EVENT_TYPE_BEGIN	= 0
TOUCH_EVENT_TYPE_MOVE	= 1
TOUCH_EVENT_TYPE_END	= 2
TOUCH_EVENT_TYPE_CANCEL	= 3
TOUCH_EVENT_TYPE_COUNT	= 3

---- UI Zorder ----
ONE_ZORDER = 0;
TWO_ZORDER = 1;
THREE_ZORDER = 2;
FOUR_ZORDER = 3;
FIVE_ZORDER = 4;
SIX_ZORDER = 5;
SEVEN_ZORDER = 6;
EIGHT_ZORDER = 7;
NINE_ZORDER = 8;
TEN_ZORDER = 9;

BACKPACK_LEFT_ZORDER = 1;
BACKPACK_LIST_ZORDER = 2;
CONFIRM_ZORDER = 10;

------GoodsType-----------

BACKPACK_DATA_TAG = 1;
STORE_DATA_TAG = 2;

WEAP_TAG = 1;
COAT_TAG = 2;
EQUIPS_TAG = 3;
PROPS_TAG = 4;
MISSION_TAG = 5;
SPRITE_EGG_TAG = 6;
SHOP_GOODS_TAG = 7;


POS_LEFT = ccp(162, 60);
POS_RIGHT = ccp(560, 21);

--背包下一级标签 背包/衣柜/精灵武器
TAG_PAGE_BASE = 123;
TAG_BANK 	= TAG_PAGE_BASE + 1;
TAG_FIGURE 	= TAG_PAGE_BASE + 2;

TAG_ALL 	= TAG_PAGE_BASE + 3;
TAG_EQUIP   = TAG_PAGE_BASE + 4;
TAG_WEAP 	= TAG_PAGE_BASE + 5;
TAG_PIECE 	= TAG_PAGE_BASE + 6;
TAG_OTHER 	= TAG_PAGE_BASE + 7;

TAG_EQUIP_PIECE = TAG_PAGE_BASE + 8;
TAG_COAT_PIECE  = TAG_PAGE_BASE + 9;



--背包下二级标签下：(背包->全部/装备/材料/其它)  (衣柜->外套/碎片)  (精灵武器->精灵)
--背包
TAG_11_ALL 			= TAG_PAGE_BASE + 11;
TAG_12_EQUIP 		= TAG_PAGE_BASE + 12;
TAG_13_EQUIP_PIECE 	= TAG_PAGE_BASE + 13;
TAG_14_OTHER 		= TAG_PAGE_BASE + 14;
--衣柜
TAG_21_COAT 	= TAG_PAGE_BASE + 21;
TAG_22_PIECE 	= TAG_PAGE_BASE + 22;
--精灵武器
TAG_31_SPRITE 	= TAG_PAGE_BASE + 31;

--仓库
TAG_BANK_ALL	= TAG_PAGE_BASE + 40;
TAG_BANK_EQUIP 	= TAG_PAGE_BASE + 41;
TAG_BANK_WEAPON = TAG_PAGE_BASE + 42;
TAG_BANK_PIECE  = TAG_PAGE_BASE + 43;
TAG_BANK_OTHER 	= TAG_PAGE_BASE + 44;

TAG_BANK_PIECE_EQUIP = TAG_PAGE_BASE + 45;
TAG_BANK_PIECE_COAT  = TAG_PAGE_BASE + 46;


FLAG_NORMAL_EQUIP 	= 1; --标志为普通装备
FLAG_GROW_EQUIP 	= 2; --标志为成长性装备

--背包中标志是否是吞噬状态
STATUS_NORMAL = 23;
STATUS_REMOVE = 24;

----------json Data Type------
--标志不同的类型json数据
-- EQUIP  = "equipBaseJson";
POINT_STAR_PRO = "pointStarPro";
POINT_STAR_USE = "pointStarUse";
NORMAL_SHOP_DATA_NAME = "generalShop";
MYSTERY_SHOP_DATA_NAME = "mysteryShop";
EXCHANGE_SHOP_DATA_NAME = "exchangeShop";
SCENE_DATA_NAME = "sceneSetData";
MAP_DATA_NAME = "LevelData";
ACTIVITY_TYPE_DATA_NAME = "ActivityTypeData";
ACTIVITY_LEVEL_DATA_NAME = "ActivityLevelData";

--物品详细信息对比面板标志
INFO_PANEL_1 = 1
INFO_PANEL_2 = 2;

--装备类型名称
GOODS_NAME_WEAP = "weapon"
GOODS_NAME_COAT = "coat"
GOODS_NAME_EQUIP = "equip"
GOODS_NAME_NORMALEQUIP = "equip_normal"
GOODS_NAME_GROWEQUIP = "equip_grow"

GOODS_NAME_HELMET_NORMAL 	= "helmet_normal"
GOODS_NAME_ARMOUR_NORMAL 	= "armour_normal"
GOODS_NAME_NECKLACE_NORMAL 	= "necklace_normal"
GOODS_NAME_RING_NORMAL 		= "ring_normal"
GOODS_NAME_SHOE_NORMAL 		= "shoes_normal"
GOODS_NAME_TROUSERS_NORMAL 	= "trousers_normal"
GOODS_NAME_GLOVE_NORMAL 	= "gloves_normal"

GOODS_NAME_HELMET_GROW 		= "helmet_grow"
GOODS_NAME_ARMOUR_GROW 		= "armour_grow"
GOODS_NAME_NECKLACE_GROW 	= "necklace_grow"
GOODS_NAME_RING_GROW 		= "ring_grow"
GOODS_NAME_SHOE_GROW 		= "shoes_grow"
GOODS_NAME_TROUSERS_GROW 	= "trousers_grow"
GOODS_NAME_GLOVE_GROW 		= "gloves_grow"


--各种装备id号起始
ID_BEGIN_WEAP = 1;
ID_END_WEAP = 5;

ID_BEGIN_COAT = 6;
ID_END_COAT = 10;

ID_BEGIN_HELMET = 11;
ID_END_HELMET = 15;

ID_BEGIN_ARMOUR = 16;
ID_END_ARMOUR = 20;

ID_BEGIN_NECKLACE = 26;
ID_END_NECKLACE = 30;

ID_BEGIN_RING = 31;
ID_END_RING = 35;

ID_BEGIN_SHOE = 36;
ID_END_SHOE = 40;

ID_BEGIN_TROUSERS = 41;
ID_END_TROUSERS = 45;

ID_BEGIN_GLOVE = 46;
ID_END_GLOVE = 50;


--标志物品信息面板类型
TAG_MUCH = 0;
TAG_LESS = 1;

--商店类型
SHOP_NOR_COUNT 		= 8;--普通商店数量
SHOP_NORMAL_BEGIN 	= 1;
SHOP_MYSTERY 	= 11;
SHOP_EXCHANGE 	= 21;

--神秘商店刷新请求类型
MYSTERY_MONEY_REFRESH 		= 1;
MYSTERY_NO_MONEY_REFRESH 	= 2;

--商店购买结果
BUY_SUCCESS = 1;
BUY_FAIL 	= 0;

---- Event ----

EVENT_TRIGGER_NONE			= 0
EVENT_TRIGGER_TAP_ACTOR		= 1
EVENT_TRIGGER_ENTER_RANGE	= 2
EVENT_TRIGGER_MOVE_VERT		= 3
EVENT_TRIGGER_INITIAL		= 4
EVENT_TRIGGER_START			= 5
EVENT_TRIGGER_UPGRADE		= 6
EVENT_TRIGGER_RECV_MISSION	= 7
EVENT_TRIGGER_FNIS_MITTION	= 8
EVENT_TRIGGER_TOTAL			= 8

EVENT_CONDITION_NONE		= 0
EVENT_CONDITION_EQUAL		= 1
EVENT_CONDITION_STRING_EQUAL= 2
EVENT_CONDITION_TOTAL		= 2

EVENT_ACTION_NONE			= 0
EVENT_ACTION_MOVE_ACTOR		= 1
EVENT_ACTION_CLOSE_EVENT	= 2
EVENT_ACTION_OPEN_EVENT		= 3
EVENT_ACTION_SWITCH_LAYER	= 4
EVENT_ACTION_OPEN_UI		= 5
EVENT_ACTION_NEW_UI			= 6
EVENT_ACTION_SET_VARIABLE	= 7
EVENT_ACTION_IF				= 8
EVENT_ACTION_ELSE			= 9
EVENT_ACTION_END			= 10
EVENT_ACTION_DIALOG			= 11
EVENT_ACTION_WAIT			= 12
EVENT_ACTION_GUIDE			= 13
EVENT_ACTION_SET_MISSION	= 14
EVENT_ACTION_SHOW_MISSION	= 15
EVENT_ACTION_UP_GRADE		= 16
EVENT_ACTION_IFBETWEEN		= 17
EVENT_ACTION_ENTER_BATTLE	= 18
EVENT_ACTION_SEND_NPCID		= 19
EVENT_ACTION_ENTER_WORLD_MAP= 20
EVENT_ACTION_ENTER_SHOP		= 21
EVENT_ACTION_TOTAL			= 21

---- Loading ----

LOADING_TYPE_SCENE			= 1
LOADING_TYPE_EVENT			= 2
LOADING_TYPE_INIT_EVENT		= 3
LOADING_TYPE_MODULE			= 4
LOADING_TYPE_PLAYERS		= 5
LOADING_TYPE_BATTLE			= 6
LOADING_TYPE_BATTLE_ASYNC	= 7
LOADING_DATA_FROM_SERVER	= 8
LOADING_DATA_MAP_AMATURE    = 9
LOADING_DATA_MAP_DATA       = 10
LOADING_FUNCS   			= 11

---- Module Key ----

MODULE_KEY_HAIR_FRONT	= "hair_front"
MODULE_KEY_HAIR_BACK	= "hair_back"
MODULE_KEY_FACE			= "face"
MODULE_KEY_EYEBROWS		= "eyebrows"
MODULE_KEY_EYES			= "eyes"
MODULE_KEY_MOUTH		= "mouth"
MODULE_KEY_GOATEE		= "goatee"
MODULE_KEY_BESHI_HAIR	= "beshi_hair"

---- Battle ----

BATTLE_ACTOR_TYPE_PLAYER	= 0
BATTLE_ACTOR_TYPE_ENEMY		= 1

BATTLE_MOVIE_BENGIN		= 0
BATTLE_MOVIE_ATTACK		= 1
BATTLE_MOVIE_END		= 2

BATTLE_KO_DEFENSER		= 1
BATTLE_KO_ATTACKER		= 2
BATTLE_KO_END			= 3--本回合是否结束
BATTLE_KO_HAND_END      = 4--本次出手结束
BATTLE_KO_DEF_VERTIGO   = 5--2眩晕
BATTLE_KO_ATK_VERTIGO   = 6--1眩晕
BATTLE_KO_DEF_DEAD   	= 7--2濒死
BATTLE_KO_ATK_DEAD   	= 8--1濒死

BATTLE_FLAG_SECOND_BUFF_DEAD = 1--新添加标志字节，是否是buff掉血掉死的
BATTLE_FLAG_SECOND_HAND_EXTRA = 2--某各技能导致下一次还是自己出手，停止头像移动
BATTLE_FLAG_SECOND_DEF_VERTIGO   = 3--2眩晕
BATTLE_FLAG_SECOND_ATK_VERTIGO   = 4--1眩晕
BATTLE_FLAG_SECOND_COUNT = 4

BATTLE_FLAG_CRITICAL	= 1--暴击
BATTLE_FLAG_HEAVY		= 2 --重击
BATTLE_FLAG_COUNTER		= 3 --反击
BATTLE_FLAG_AVOID		= 4 --闪避
BATTLE_FLAG_BLOCK		= 5 --
BATTLE_FLAG_FEEDBACK	= 6 --是否是永久技能
BATTLE_FLAG_COMBO		= 7
BATTLE_FLAG_CANCEL		= 8
BATTLE_FLAG_COUNT		= 8

BATTLE_FLAG_SKILL		= 9

MOVIE_INTERRUPT_TYPE_NONE		= 0
MOVIE_INTERRUPT_TYPE_COMBO		= 1
MOVIE_INTERRUPT_TYPE_COUNTER	= 2
MOVIE_INTERRUPT_TYPE_CANCEL		= 3

BATTLE_BUFF_TYPE_ANIMATION	= 1
BATTLE_BUFF_TYPE_COLOR		= 2
BATTLE_BUFF_TYPE_SHOCK		= 3
BATTLE_BUFF_TYPE_DOA		= 4

SHOCK_DIR_HORIZONTAL	= 0;
SHOCK_DIR_VERTICAL		= 1;

BATTLE_ACTOR_MOVE_NONE	= 0;
BATTLE_ACTOR_MOVE_TO	= 1;
BATTLE_ACTOR_MOVE_BY	= 2;

BATTLE_TURN_COLOR_NONE		= 0;
BATTLE_TURN_COLOR_SCREEN	= 1;
BATTLE_TURN_COLOR_ACTOR		= 2;

BATTLE_EFFECT_MOVE_NONE		= 0;
BATTLE_EFFECT_MOVE_INTERVAL	= 1;
BATTLE_EFFECT_MOVE_INSTANT	= 2;

BATTLE_STATE_NONE = 0;
BATTLE_STATE_ATTACK = 1;
BATTLE_STATE_WAIT   = 2;
BATTLE_STATE_COMBO = 3;--连击
BATTLE_STATE_COUNTER = 4;--反击
BATTLE_STATE_NEXT  = 5;
BATTLE_STATE_BEGIN = 6;
BATTLE_STATE_RELIVE = 7;
BATTLE_STATE_PREPARE_RELIVE = 8;
BATTLE_STATE_PAUSE_ROLL = 9;


FINAL_ATTACK_TYPE_NORMAL = 0;--正常打击
FINAL_ATTACK_TYPE_FLY = 1;--击飞
FINAL_ATTACK_TYPE_BACK = 2;--击退
FINAL_ATTACK_TYPE_CONTINUE = 4;--连击中的第二击
--------Goods Position---------

MAIL_GOODS = 1;


WINSIZE = CCDirector:sharedDirector():getWinSize();
BLACK_COLOR4 = ccc4(0,0,0,180);
BLACK_COLOR4_OPAC = ccc4(0,0,0,0);


--------TimeRefresh pos-----------
SHOP_MYS_TIME = 1;
SHOP_EXC_TIME = 2;
JJC_TIME 	  = 3;
JJC_TIME 	  = 3;


GROUP_COUNT = 7;
UI_STATE_CONTINUE 	= 1;
UI_STATE_STOP     	= 2;--本次出手结束
UI_STATE_ATTACK   	= 3;
UI_STATE_INTERVAL 	= 4;--一回合结束
UI_STATE_EQUAL 	    = 5;--两个人速度相等的时候临时状态
UI_STATE_NONE       = 6;

BUFF_TYPE_Attack = 1;
BUFF_TYPE_DEFEND = 2;

--技能中要给敌人位移的类型，0伤害位移，普通位移，2上DOT类型
SKILL_MOVE_DAMAGE = 0;
SKILL_MOVE_NORMAL = 1;
SKILL_MOVE_BUFF = 2;



STATUS_TEST = 1;
STATUS_TRUE = 2;

--全局消息队列类型定义

MAP_TMX_COUNT_PRE = 1000;
GLOBAL_MESSAGE_MONEY = 1;
GLOBAL_MESSAGE_ENERGY = 2;
GLOBAL_MESSAGE_DIAMOND = 3;
GLOBAL_MESSAGE_COMMON = 4;--切换普通模式
GLOBAL_MESSAGE_ELITE = 5;
GLOBAL_MESSAGE_MAP = 6;
GLOBAL_MESSAGE_ARROW = 7;--如果进入选关界面需要提示打某个关卡发送的消息
GLOBAL_MESSAGE_BACK = 8;--通用ui界面最上层返回消息
GLOBAL_MESSAGE_ACTIVITY_TYPE = 9;
GLOBAL_MESSAGE_BACK_ACTIVITY = 10;--返回副本活动界面 

DATA_BASE_ACTIVITY_LEVEL = "ActivityLevelData";--存储数据的lua文件
DATA_BASE_ACTIVITY_TYPE = "ActivityTypeData";
DATA_BASE_MAP_LEVEL = "LevelData";

BATTLE_TYPE_COMMON = 1;
BATTLE_TYPE_ACTIVITY = 2;

COLOR_WHITE	= 1;
COLOR_GREEN	= 2;
COLOR_BLUE	= 3;
COLOR_PURPLE= 4;
COLOR_ORANGE= 5;
COLOR_RED   = 6;


COLOR_VALUE = {
	ccc3(255, 255, 255), 	--白
	ccc3(0, 255, 0),     	--绿
	ccc3(0, 25, 255), 		--蓝
	ccc3(200, 0, 255), 		--紫
	ccc3(255, 200, 0), 		--橙
	ccc3(255, 0, 0),		--红
};


--捏脸两种状态(创建角色时；更改捏脸)
FACEMAKER_STATUS_CREATE = 1;
FACEMAKER_STATUS_CHANGE = 2;


BATTLE_MAIN_TYPE_PVE = 1;
BATTLE_MAIN_TYPE_PVP = 2;

BATTLE_SUBTYPE_LEVEL = 1;--推关
BATTLE_SUBTYPE_ACTIVITY = 2;--活动副本
BATTLE_SUBTYPE_REWARD = 3;--赏金
BATTLE_SUBTYPE_JJC = 4;--竞技场
BATTLE_SUBTYPE_TRAIN = 5;--训练场
BATTLE_SUBTYPE_TOURNAMENT = 100;


BACKPACK_FIGURE 		 = 1;
BACKPACK_FIGURE_PROPERTY = 2;
BACKPACK_FIGURE_WEAPON 	 = 3;


OPE_RESULT_EQUIP_MONEY_NOT_ENOUGH = 115;--金钱不足
OPE_RESULT_EQUIP_TOKEN_NOT_ENOUGH = 116;-- 元宝不足


BROADCAST_COLOR_WHITE = ccc3(255,255,255);
BROADCAST_COLOR_GREEN = ccc3(0,255,0);
BROADCAST_COLOR_BLUE = ccc3(0,0,255);
BROADCAST_COLOR_PURPLE = ccc3(125,46,137);
BROADCAST_COLOR_ORANGE = ccc3(251,120,13);
BROADCAST_COLOR_GOLD = ccc3(238,238,9);


CHAT_TYPE_ALL = 1
CHAT_TYPE_WORLD = 2
CHAT_TYPE_TEAM = 3
CHAT_TYPE_SYSTEM = 4

DATABASE_HEAD = "id_";



UPSTEP_GOODS_OTHER_POS = ccp(430, 130);


GOODS_COUNT_TOTAL_1 = 80;
GOODS_COUNT_TOTAL_2 = 120;