------ Root Path ------

PATH_SCRIPT_ROOT = "Scripts/"
PATH_RES_ROOT = "Res/"
PATH_USER_ROOT = "User/"

------ Script Path ------

PATH_SCRIPT_BATTLE = PATH_SCRIPT_ROOT .. "Battle/"
PATH_SCRIPT_COCOS = PATH_SCRIPT_ROOT .. "Cocos2d/"
PATH_SCRIPT_CONST = PATH_SCRIPT_ROOT .. "Const/"
PATH_SCRIPT_EVENT = PATH_SCRIPT_ROOT .. "Event/"
PATH_SCRIPT_PLAYER = PATH_SCRIPT_ROOT .. "Player/"
PATH_SCRIPT_SCENE = PATH_SCRIPT_ROOT .. "Scene/"
PATH_SCRIPT_SYSTEM = PATH_SCRIPT_ROOT .. "System/"
PATH_SCRIPT_UI = PATH_SCRIPT_ROOT .. "UI/"
PATH_SCRIPT_PLAYER = PATH_SCRIPT_ROOT .. "Player/"
PATH_SCRIPT_SCENE_MISSION = PATH_SCRIPT_SCENE .. "Mission/"
PATH_SCRIPT_UI_FRIEND = PATH_SCRIPT_UI .. "Friends/"
PATH_SCRIPT_UI_TRAIN = PATH_SCRIPT_UI .. "Train/"
PATH_SCRIPT_UI_EQUIPANEL = PATH_SCRIPT_UI .. "EquipPanel/"


------ Resource Path ------
PATH_RES_AUDIO = PATH_RES_ROOT .. "Audio/"
PATH_RES_ANIM = PATH_RES_ROOT .. "Animations/"
PATH_RES_BATTLE = PATH_RES_ROOT .. "Battle/"
PATH_RES_DATA = PATH_RES_ROOT .. "Data/"
PATH_RES_EVENT = PATH_RES_ROOT .. "Event/"
PATH_RES_MODULE = PATH_RES_ROOT .. "Modules/"
PATH_RES_IMAGE = PATH_RES_ROOT .. "Image/"
PATH_RES_SCENE = PATH_RES_ROOT .. "Scene/"
PATH_RES_UI = PATH_RES_ROOT .. "UI/"
PATH_RES_MAP = PATH_RES_ROOT .. "Map/"
PATH_RES_MAP_ICON = PATH_RES_MAP .. "icon/"

PATH_CCS_RES = PATH_RES_UI .. "ccsres/"
PATH_RES_UI_EQUIPANEL = PATH_RES_UI .. "equipPanel/"

PATH_CCS_RES_LABEL_IMG	= PATH_CCS_RES .. "LabelImg/"

PATH_RES_ACTORS = PATH_RES_ANIM .. "Actors/"
PATH_RES_EFFECT = PATH_RES_ANIM .. "Effect/"
PATH_RES_LABEL = PATH_RES_ANIM .. "Label/"
PATH_RES_PLAYER = PATH_RES_ANIM .. "Player/"
PATH_RES_OTHER = PATH_RES_ANIM .. "Other/"
PATH_RES_WEAPONS = PATH_RES_ANIM .. "Weapons/"


PATH_RES_BAT_ACTOR = PATH_RES_BATTLE .. "Actor/"
PATH_RES_BAT_BG = PATH_RES_BATTLE .. "Background/"

PATH_RES_MDL_BATTLE = PATH_RES_MODULE .. "Battle/"
PATH_RES_MDL_SCENE = PATH_RES_MODULE .. "Scene/"
PATH_RES_MDL_MALE = PATH_RES_MODULE .. "Male/"

PATH_RES_MDL_SCENE_MALE = PATH_RES_MDL_SCENE .. "Male/"
PATH_RES_MDL_SCENE_FEMALE = PATH_RES_MDL_SCENE .. "Female/"

PATH_RES_IMG_WEAPON = PATH_RES_IMAGE .. "weapon/"
PATH_RES_IMG_COAT = PATH_RES_IMAGE .. "coat/"
PATH_RES_IMG_EQUIPS = PATH_RES_IMAGE .. "Equips/"
PATH_RES_IMG_MAP = PATH_RES_IMAGE .. "MiniMap/"
PATH_RES_IMG_MONEY = PATH_RES_IMAGE .. "money/"
PATH_RES_IMG_WARDROBE	= PATH_RES_IMAGE .. "wardrobe/"
PATH_RES_IMG_SKILLS		= PATH_RES_IMAGE .. "skills/"
PATH_RES_IMG_FACEMAKER	= PATH_RES_IMAGE .. "facemaker/"
PATH_RES_IMG_ICON = PATH_RES_IMAGE .. "buff_icon/"
PATH_RES_IMG_SHOP = PATH_RES_IMAGE .. "shop/"


PATH_RES_IMAGE_SKILLS_NORMAL   = PATH_RES_IMG_SKILLS .. "normal/"
PATH_RES_IMAGE_SKILLS_DISABLE  = PATH_RES_IMG_SKILLS .. "disable/"

PATH_RES_IMAGE_WARDROBE_NORMAL = PATH_RES_IMG_WARDROBE .. "normal/"
PATH_RES_IMAGE_WARDROBE_DISABLE = PATH_RES_IMG_WARDROBE .. "disable/"


--赏金任务人物头像

PATH_RES_IMAGE_HUNTER = PATH_RES_IMAGE.."task/hunter/"
PATH_RES_IMAGE_MAJOR = PATH_RES_IMAGE.."task/major/"

--英雄人物头像拼图路径
PATH_RES_IMAGE_HEAD_FACE= PATH_RES_IMAGE.."head/face/"
PATH_RES_IMAGE_HEAD_HAIR= PATH_RES_IMAGE.."head/hair/"
PATH_RES_IMAGE_HEAD_COAT= PATH_RES_IMAGE.."head/coat/"
PATH_RES_IMAGE_HEAD_COLOR=PATH_RES_IMAGE.."head/color/"


--远古
PATH_RES_IMAGE_ANCIENT_UNGET=PATH_RES_IMAGE.."ancient_unget/"